### PR TITLE
Heightprofile support for 3D-units

### PR DESCRIPTION
**Pull request by mhieta**
## Description

Add Heightprofile support for 3D-units.

Highlights:
- Add leaflet.heightgraph and d3 to project
- Add HeightProfileControl to project
- Migrate and adapt application to React Leaflet v4 and React-Leaflet-Core v2
- Support both LineString- and MultiLineString-geometries
- Allow Unit MultiLineString scrolling

## Screenshots
height profile

### CODE REVIEW

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr261.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr261.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr261.dev.hel.ninja** :rocket::rocket::rocket:

**Review by japauliina — APPROVED** [review]
Awesome! 📈

**Pull request merged**
