### PR TITLE
Fix links to repo

### PR DESCRIPTION
**Pull request by hugovk**
```diff
-https://github.com/nordsoftware/outdoors-sports-map
+https://github.com/City-of-Helsinki/outdoors-sports-map
```

Do you still need the old repo at https://github.com/digiaonline/outdoors-sports-map or can we archive  it? Thanks!

Also, is it intentional to disable issues in this repo?

### CODE REVIEW

**Comment by Jokinen** [comment]
I'm still trying to get a final confirmation for this. I'm rather certain that it'd be fine to archive the repo, but I don't know that much about this project, so I'm making sure.

**Comment by hugovk** [comment]
Thanks for checking! No rush on our side.

**Comment by pjlampil** [comment]
> Thanks for checking! No rush on our side.

Yes it's ok to archive the repo

**Review by pjlampil — APPROVED** [review]
LGTM

**Comment by Jokinen** [comment]
Apologies, this has been left unmerged. Thank you for resolving the conflicts. These changes will be reflected in the live application after the next production update.

**Pull request merged**
