### PR TITLE
End paragraph with fullstop / Reporting invalid HTTPS certificate

### PR DESCRIPTION
**Pull request by hugovk**
The main point of this PR is to report an issue, which I can't do because they've been disabled from this repo.

The HTTPS certificate is invalid for this site, which means the site is unusable:

https://www.ulkoliikunta.fi/

image

image

### CODE REVIEW

**Comment by hugovk** [comment]
I see https://ulkoliikunta.fi/ is working (no www), but the www is broken.

**Comment by Jokinen** [comment]
@hugovk Thank you for pointing out these issue even when the repo hasn't made it easy!

Apologies that it has taken so long for you to receive a reply. I'll try to get attention for this and your other concern.

**Comment by Jokinen** [comment]
We are looking at your concerns, in the meanwhile I've asked for issues to be enabled for this repo so that it's easier to report problems in the future. They should be accessible now.

**Review by Jokinen — APPROVED** [review]
The www address should be working now! Again, thank you for the taking the time to point it out.

https://www.ulkoliikunta.fi/

**Comment by hugovk** [comment]
Great, thanks!

It might be an idea to have a "single source of truth" and redirect one to the other. That way things like language choice should persist.

**Comment by Jokinen** [comment]
Good suggestion! We're looking into what's the easiest way to make it happen.

**Comment by Jokinen** [comment]
I've added a ticket into our task tracking. We'll try to find a solution that's usable between services.

Do you have any other concerns?

**Comment by hugovk** [comment]
All good, thank you!

**Pull request merged**
