### PR TITLE
Add HDS CookieConsent modal

### PR DESCRIPTION
**Pull request by japauliina**
## Description

Add Helsinki Design System CookieConsent modal to the page.

## Context

Refs [HUL-12](https://andersinno.atlassian.net/browse/HUL-12)

## How Has This Been Tested?

Tested in local development environment.

## Screenshots
Example of the whole modal:
fi

Also support for English and Swedish:
en

### CODE REVIEW

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr240.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr240.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr240.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**ULKOLIIKUNTAKARTTA-UI branch is deployed to platta: https://ulkoliikunta-pr240.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mhieta — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
