### PR TITLE
ULK-93 | Add jump link

### PR DESCRIPTION
**Pull request by Jokinen**
## Description

Add a jump to content link to the beginning of the page.

It should be hidden by default, but become visible when focused. It should be the first focusable element on the page. The should move the user's focus to the main content, skipping any repeated content.

Note that currently there's no repeated content on this application so nothing is skipped.

## Context

[ULK-93](https://helsinkisolutionoffice.atlassian.net/browse/ULK-93)

## How Has This Been Tested?

I've added unit level tests which check the new JumpLink and Page components.

## Manual Testing Instructions for Reviewers

While using a screen reader

1. Expect to see no skip to content link by default
2. When tabbing into the page expect jump to content link to become visible
3. Expect link to move focus into main content

### CODE REVIEW

**Review by tuovinensanttu — COMMENTED** [review]
`Jump to content` is working correctly on Chrome and Safari, but Firefox jumps straight to input field. Also there is something sketchy going on with the map; As soon as I change branch to this one (with or without restarting) map stops working and only thing I see is white screen (search and language are shown).

**Comment by Jokinen** [comment]
I used the review environment to validate your concern https://outdoors-sports-map-feature-ul-6a.newtest.kuva.hel.ninja/

The map seems to be missing. I'll debug.

**Comment by Jokinen** [comment]
The missing map was caused by style changes which happened because the element hierarchy of the application changed. Two new element were added higher up in the DOM hierarchy. They wrapped the map, but did not have `height: 100%` which in turn resulted in `height: 0`, as well as a hidden map.

**Comment by tuovinensanttu** [comment]
Map is now working, but `Jumo to content` button is still not working on Firefox.

**Comment by Jokinen** [comment]
This is an odd issue. I compared our solution with vero.fi to find a a difference which could explain the behaviour.

However, I noticed that the vero.fi skip-to-content-link does not seem to work either.

I'll try to debug some more. I currently assume that it's something to do with Firefox being stricter about what it allows to be focused. Styles work correctly if I apply the focus manually. It seems that Firefox thinks that the link should not get focus for some reason.

**Comment by Jokinen** [comment]
I was able to make the jump link work after following these instructions: https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox

As far as I understood, it's a configuration issue.

**Review by tuovinensanttu — APPROVED** [review]
Pff, of course it was a missing setting in my end 🤦  working now. Nice work!

**Comment by Jokinen** [comment]
To be fair that setting is super hard to find and I wouldn't expect users to have set it. But I couldn't find another reasonable way to make it work. I did try a variety of hacks as well.

**Comment by Jokinen** [comment]
Rebase to resolve conflicts.

**Pull request merged**
